{{--
  Math + honeypot CAPTCHA. Drop into any form before the submit button:
      @include('partials.captcha')
  Server side: validate captcha_answer with the App\Rules\Captcha rule.

  - $challenge is auto-generated by App\Services\CaptchaService when the
    partial is included; you don't need to inject anything.
  - The honeypot field (captcha_hp) is visible only to bots — kept in the
    DOM but pushed off-screen, with tabindex=-1 + autocomplete=off so real
    users (including screen-reader users) skip past it.
--}}
@php
    $captchaSvc = app(\App\Services\CaptchaService::class);
    $challenge = $captchaSvc->challenge();
@endphp

<div class="space-y-1">
    <label class="block text-sm mb-1" for="captcha_answer">
        Verify you're human
    </label>
    <div class="flex items-center gap-3 rounded-md border border-slate-700 bg-slate-900 px-3 py-2">
        <span class="font-display text-sm uppercase tracking-[0.15em] text-slate-300 whitespace-nowrap">
            {{ $challenge['question'] }}
        </span>
        <input id="captcha_answer" name="captcha_answer" type="text" inputmode="numeric"
            autocomplete="off" required
            placeholder="Answer"
            class="flex-1 rounded-md bg-slate-950 border border-slate-700 px-2 py-1 text-slate-100 focus:outline-none focus:border-[var(--chrono-blue,#22d3ee)]/60">
    </div>
    @error('captcha_answer')
        <p class="text-sm text-rose-400 mt-1">{{ $message }}</p>
    @enderror
    <p class="text-[0.65rem] text-slate-500">
        Helps keep automated bots out of the form.
    </p>

    <input type="hidden" name="captcha_token" value="{{ $challenge['token'] }}">

    {{-- Honeypot. Bots that scrape every input fill this; humans never see
         it. CSS-hidden in three ways for resilience (display:none alone
         is suspicious to some bots — combining it with off-screen + zero
         opacity catches more cases). --}}
    <div aria-hidden="true" style="position:absolute; left:-10000px; top:auto; width:1px; height:1px; overflow:hidden; opacity:0;">
        <label for="captcha_hp">Website (leave blank)</label>
        <input id="captcha_hp" name="captcha_hp" type="text" tabindex="-1" autocomplete="off" value="">
    </div>
</div>
